Controllers/ChannelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TimeSheet.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TimeSheet.Controllers
{
    public class ChannelController : Controller
    {
        private readonly TimeSheetDbContext _dbcontext;

        public ChannelController(TimeSheetDbContext dbcontext)
        {
            _dbcontext = dbcontext;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }


        public JsonResult GetAllData()
        {
            var jsonValues = Json(_dbcontext.Channels.ToList());
            return jsonValues;
        }


        [HttpPost]
        public IActionResult DeleteRecord([FromBody] tmpValues rs)
        {

            var myActivity = (from c in _dbcontext.Channels
                              where c.Id == Convert.ToInt32(rs.id)
                              select c).FirstOrDefault();

            _dbcontext.Channels.Remove(myActivity);
            _dbcontext.SaveChanges();

            return Json(new { msg = "Successfully added " });

        }

        [HttpPost("SaveChannel")]
        public IActionResult SaveChannel([FromBody] Channel rs)

        {
            int tmpID = System.Convert.ToInt32(rs.Id.ToString());
            var dbStudent = _dbcontext.Channels.Where(s => s.Id == System.Convert.ToInt32(tmpID)).FirstOrDefault();


            if (rs != null)
            {
                if (rs.Id == 0)
                {
                    _dbcontext.Add(rs);
                }
                else
                {
                    dbStudent.ChannelName = rs.ChannelName;
                }

                _dbcontext.SaveChanges();
                return Json(new { msg = "Successfully added " });
            }
            else
            {
                return Json(new { msg = "Fail added " });
            }
        }
    }
}

Controllers/JobtypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TimeSheet.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TimeSheet.Controllers
{
    public class JobtypeController : Controller
    {

        private readonly TimeSheetDbContext _dbcontext;

        public JobtypeController(TimeSheetDbContext dbcontext)
        {
            _dbcontext = dbcontext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public JsonResult GetAllData()
        {
            var jsonValues = Json(_dbcontext.Jobtypes.ToList());
            return jsonValues;
        }


        [HttpPost]
        public IActionResult DeleteRecord([FromBody] tmpValues rs)
        {

            var myActivity = (from c in _dbcontext.Jobtypes
                              where c.Id == Convert.ToInt32(rs.id)
                              select c).FirstOrDefault();

            _dbcontext.Jobtypes.Remove(myActivity);
            _dbcontext.SaveChanges();

            return Json(new { msg = "Successfully added " });

        }

        [HttpPost("SaveJobtype")]
        public IActionResult SaveJobtype([FromBody] Jobtype rs)

        {
            int tmpID = System.Convert.ToInt32(rs.Id.ToString());
            var dbStudent = _dbcontext.Jobtypes.Where(s => s.Id == System.Convert.ToInt32(tmpID)).FirstOrDefault();


            if (rs != null)
            {
                if (rs.Id == 0)
                {
                    _dbcontext.Add(rs);
                }
                else
                {
                    dbStudent.Descriptions=rs.Descriptions;
                }

                _dbcontext.SaveChanges();
                return Json(new { msg = "Successfully added " });
            }
            else
            {
                return Json(new { msg = "Fail added " });
            }
        }
    }
}
    

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TimeSheet.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TimeSheet.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly TimeSheetDbContext _dbcontext;

        public ProjectsController(TimeSheetDbContext dbcontext)
        {
            _dbcontext = dbcontext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        // to get data for show on data table index views.
        public JsonResult GetAllData()
        {
            var dbProject = (from project in _dbcontext.Projects
                             join tmlchannel in _dbcontext.Channels on project.ChannelId equals tmlchannel.Id
                             join tmldepartment in _dbcontext.Departments on project.DepartmentId equals tmldepartment.Id
                             join tmljobtype in _dbcontext.Jobtypes on project.ProjectTypeId equals tmljobtype.Id
                             select new
                             {
                                     projectId = project.Id,
                                     projectCode = project.ProjectCode,
                                     projectrefrence = project.ReferenceNo,
                                     projectDescription = project.Descriptions,
                                     projectType = tmljobtype.Descriptions,
                                     ChannelsName = tmlchannel.ChannelName,
                                     departmentName = tmldepartment.DepartmentName
                             }).ToList();
            var jsonValues = Json(dbProject);
            return jsonValues;
        }

        // to poppulate department combobox
        public JsonResult GetDepartment()
        {
            var jsonValue = Json(_dbcontext.Departments.ToList());
            return jsonValue;
        }

        //to populate channel commbobox
        public JsonResult GetChannel()
        {
            var jsonValue = Json(_dbcontext.Channels.ToList());
            return jsonValue;
        }

        //to populate jobtype combobox
        public JsonResult GetJobType()
        {
            var jsonvalue = Json(_dbcontext.Jobtypes.ToList());
            return jsonvalue;
        }

        // to Delete records 
        [HttpPost]
        public IActionResult DeleteRecord([FromBody] tmpValues rs)
        {
            var project = (from c in _dbcontext.Projects
                           where c.Id == Convert.ToInt32(rs.id)
                           select c).FirstOrDefault();

            _dbcontext.Projects.Remove(project);
            _dbcontext.SaveChanges();

            return Json(new { msg = "Successfully added " });
        }

        // to save data and update data to database 

        [HttpPost("SaveProjcts")]
        public IActionResult SavePojects([FromBody] Project rs)

        {
            int tmpID = System.Convert.ToInt32(rs.Id.ToString());
            var dbproject = _dbcontext.Projects.Where(s => s.Id == System.Convert.ToInt32(tmpID)).FirstOrDefault();

            if (rs != null)
            {
                if (rs.Id == 0)
                {
                    _dbcontext.Add(rs);
                }
                else
                {
                    dbproject.Descriptions = rs.Descriptions;
                    dbproject.ProjectTypeId = rs.ProjectTypeId;
                    dbproject.ChannelId = rs.ChannelId;
                    dbproject.DepartmentId = rs.DepartmentId;
                }

                _dbcontext.SaveChanges();
                return Json(new { msg = "Successfully added " });
            }
            else
            {
                return Json(new { msg = "Fail added " });
            }
        }
    }
}

Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TimeSheet.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TimeSheet.Controllers
{
    public class RolesController : Controller
    {
        private readonly TimeSheetDbContext _dbcontext;

        public RolesController(TimeSheetDbContext dbcontext)
        {
            _dbcontext = dbcontext;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }


        public JsonResult GetAllData()
        {
            var jsonValues = Json(_dbcontext.Roles.ToList());
            return jsonValues;
        }


        [HttpPost]
        public IActionResult DeleteRecord([FromBody] tmpValues rs)
        {

            var employee = (from c in _dbcontext.Roles
                            where c.Id == Convert.ToInt32(rs.id)
                            select c).FirstOrDefault();

            _dbcontext.Roles.Remove(employee);
            _dbcontext.SaveChanges();

            return Json(new { msg = "Successfully added " });

        }

        [HttpPost("SaveRoles")]
        public IActionResult SaveRoles([FromBody] Role rs)

        {
            int tmpID = System.Convert.ToInt32(rs.Id.ToString());
            var dbStudent = _dbcontext.Roles.Where(s => s.Id == System.Convert.ToInt32(tmpID)).FirstOrDefault();


            if (rs != null)
            {
                if (rs.Id == 0)
                {
                    _dbcontext.Add(rs);
                }
                else
                {
                    dbStudent.RoleName = rs.RoleName;
                }

                _dbcontext.SaveChanges();
                return Json(new { msg = "Successfully added " });
            }
            else
            {
                return Json(new { msg = "Fail added " });
            }
        }
    }
}

Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="float-right">
        @ViewBag.Events
    </div>
    <div>
        <strong>Copyright</strong> Tokiomarine Life Insurance PLC &copy; 2019 - 2020
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IT-Time sheet</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/animate.css" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/css/animate.css" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    </environment>


</head>
<body>


    <!-- Wrapper-->
    <div id="wrapper" class="@Html.PageClass()">

        <!-- Navigation -->
        <partial name="_Navigation" />

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">

            <!-- Top Navbar -->
            <partial name="_TopNavbar" />

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            <partial name="_Footer" />

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/Popper/popper.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/metisMenu/dist/jquery.metisMenu.js"></script>
        <script src="~/lib/slimScroll/jquery.slimscroll.js"></script>
        <script src="~/lib/pace/pace.js"></script>
        <script src="~/js/script.js" asp-append-version="true"></script>

        <!-- Only for demo purpose -->
        <script src="~/js/skin.config.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/Popper/popper.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/lib/metisMenu/dist/jquery.metisMenu.js"></script>
        <script src="~/lib/pace/pace.min.js"></script>
        <script src="~/lib/slimScroll/jquery.slimscroll.min.js"></script>
        <script src="~/js/script.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Navigation.cshtml
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="block m-t-xs font-bold">Username</span>
                        <span class="text-muted text-xs block">Title <b class="caret"></b></span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs" style="position: absolute; top: 91px; left: 0px; will-change: top, left;">
                        <li><a class="dropdown-item" href="#">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    TMLTH
                </div>
            </li>

            <li class="@Html.IsSelected(controller: "Home")">
                <a href="#"><i class="fa fa-bar-chart-o"></i> <span class="nav-label" data-i18n="nav.forms">Time sheet</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse @Html.IsSelected(controller: "Graphs", cssClass: "in")">
                    <li class="@Html.IsSelected(action: "Flot")"><a href="@Url.Action("index", "TimeSheets")">Log timesheet</a></li>
                    <li class="@Html.IsSelected(action: "Morris")"><a href="@Url.Action("#", "Home")">Dashbaord</a></li>
                </ul>
            </li>

            <li class="@Html.IsSelected(controller: "Home")">
                <a href="#"><i class="fa fa-server"></i> <span class="nav-label" data-i18n="nav.forms">Master setup</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse @Html.IsSelected(controller: "Graphs", cssClass: "in")">
                    <li class="@Html.IsSelected(action: "Flot")"><a href="@Url.Action("index", "Channel")">Channels</a></li>
                    <li class="@Html.IsSelected(action: "Morris")"><a href="@Url.Action("index", "Department")">Departments</a></li>
                    <li class="@Html.IsSelected(action: "Rickshaw")"><a href="@Url.Action("index", "Activities")">Activities</a></li>
                    <li class="@Html.IsSelected(action: "Chartjs")"><a href="@Url.Action("index", "Projects")">Projects</a></li>
                    <li class="@Html.IsSelected(action: "Chartist")"><a href="@Url.Action("Chartist", "Graphs")">Accounts</a></li>
                    <li class="@Html.IsSelected(action: "C3charts")"><a href="@Url.Action("index", "EmployeeType")">Employee type</a></li>
                    <li class="@Html.IsSelected(action: "Peity")"><a href="@Url.Action("index", "Jobtype")">Job type</a></li>
                    <li class="@Html.IsSelected(action: "Sparkline")"><a href="@Url.Action("index", "Roles")">Roles</a></li>
                    <li class="@Html.IsSelected(action: "Sparkline")"><a href="@Url.Action("index", "SectionDept")">Section</a></li>
                </ul>
            </li>
 
        </ul>
    </div>
</nav>

Views/Shared/_TopNavbar.cshtml
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li style="padding:20px">
                <span class="m-r-sm text-muted welcome-message">Welcome to TMLTH-Time sheets</span>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-sign-out"></i> Log out
                </a>
            </li>
        </ul>
    </nav>
</div>