Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TimeSheet.Models;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TimeSheet.Controllers
{
    public class ActivitiesController : Controller
    {

        private readonly TimeSheetDbContext _conntext;

        public ActivitiesController(TimeSheetDbContext context)
        {
            _conntext = context;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }
        //get data to show on scfreen
        public JsonResult GetAllData()
        {
            var jsonValues = Json(_conntext.Acitivities.ToList());
            return jsonValues;
        }

         
        [HttpPost]
        public IActionResult DeleteRecord([FromBody] tmpValues rs)
        {

                var myActivity = (from c in _conntext.Acitivities
                                  where c.Id == Convert.ToInt32(rs.id)
                                  select c).FirstOrDefault();

            _conntext.Acitivities.Remove(myActivity);
            _conntext.SaveChanges();

            return Json(new { msg = "Successfully added " });

        }



        [HttpPost("SaveData")]
        public IActionResult SaveData([FromBody] Acitivity rs)

        {
            int tmpID = System.Convert.ToInt32(rs.Id.ToString());
            var dbStudent = _conntext.Acitivities.Where(s => s.Id == System.Convert.ToInt32(tmpID)).FirstOrDefault();


            if (rs != null)
            {
                if (rs.Id == 0)
                {
                    _conntext.Add(rs);
                }
                else
                {
                    dbStudent.ActivityName = rs.ActivityName;
                }

                _conntext.SaveChanges();
                return Json(new { msg = "Successfully added " });
            }
            else
            {
                return Json(new { msg = "Fail added " });
            }
        }
    }
}

Views/Activities/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Activities</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Dashboard_1", "Dashboards")">Home</a>
            </li>
            <li class="breadcrumb-item">
                <a>Activities</a>
            </li>
            <li class="active breadcrumb-item">
                <strong>Create</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <div class="ibox ">
            <div class="ibox-title">
                <h5>Create <small>Activities data Master</small></h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#" class="dropdown-item">Config option 1</a>
                        </li>
                        <li>
                            <a href="#" class="dropdown-item">Config option 2</a>
                        </li>
                    </ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                    <div class="hr-line-dashed"></div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Activities :</label>
                        <div class="col-sm-10">
                            <input type="text" id="ActivityName" class="form-control"> <span class="form-text m-b-none">Example Develop,Analysis and Design..</span>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group row">
                        <div class="col-sm-4 col-sm-offset-2">
                            <button class="btn btn-white btn-sm" type="submit">Cancel</button>
                            <button class="btn btn-primary btn-sm" id="btnSave" type="submit">Save changes</button>
                        </div>
                    </div>
            </div>
        </div>
    </div>


@section Scripts

{  
    <script type="text/javascript">  
    $(function () {

        $("#btnSave").click(function () {

            var fullDate = new Date();
            var twoDigitMonth = fullDate.getMonth() + ""; if (twoDigitMonth.length == 1) twoDigitMonth = "0" + twoDigitMonth;
            var twoDigitDate = fullDate.getDate() + ""; if (twoDigitDate.length == 1) twoDigitDate = "0" + twoDigitDate;
            var currentDate = twoDigitDate + "/" + twoDigitMonth + "/" + fullDate.getFullYear(); console.log(currentDate);
      
            var param = {
                 
                ActivityName: $("#ActivityName").val(),
                CrtUser: "Banphotkho",
                CrtDate: fullDate
            }
            $.ajax({
                type: "POST",
                url: '@Url.Action("SaveData", "Activities")',
                contentType: 'application/json; charset=utf-8',
                dataType: "json",
                data: JSON.stringify(param),
                success: function () {
                    alert("Data has been added successfully.");
                    //LoadData();  
                },
                error: function () {
                    alert("Error while inserting data");
                }
            });
            return false;
        });
    });

    function LoadData() {
        $("#tblStudent tbody tr").remove();
        $.ajax({
            type: 'POST',
            url: '@Url.Action("getStudent")',
            dataType: 'json',
            data: { id: '' },
            success: function (data) {
                var items = '';
                $.each(data, function (i, item) {
                    var rows = "<tr>"
                        + "<td class='prtoducttd'>" + item.studentID + "</td>"
                        + "<td class='prtoducttd'>" + item.studentName + "</td>"
                        + "<td class='prtoducttd'>" + item.studentAddress + "</td>"
                        + "</tr>";
                    $('#tblStudent tbody').append(rows);
                });
            },
            error: function (ex) {
                var r = jQuery.parseJSON(response.responseText);
                alert("Message: " + r.Message);
                alert("StackTrace: " + r.StackTrace);
                alert("ExceptionType: " + r.ExceptionType);
            }
        });
        return false;
    }
    </script>  
}  